import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'pl' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  pl: {
    // Navigation
    'nav.home': 'Strona Główna',
    'nav.matches': 'Mecze',
    'nav.results': 'Wyniki',
    'nav.teams': 'Drużyny',
    'nav.contact': 'Kontakt',
    'nav.login': 'Zaloguj się',
    'nav.register_team': 'Zapisz drużynę',
    
    // Account page
    'account.title': 'Moje Konto',
    'account.steam_connection': 'Połączenie Steam',
    'account.steam_connected': 'Konto Steam połączone',
    'account.steam_not_connected': 'Konto Steam niepołączone',
    'account.steam_required': 'Aby utworzyć drużynę lub dołączyć jako członek, musisz połączyć swoje konto Steam.',
    'account.connect_steam': 'Połącz konto Steam',
    'account.info': 'Informacje o koncie',
    'account.email': 'Email',
    'account.nickname': 'Nick',
    'account.steam': 'Steam',
    'account.connected': 'Połączone',
    'account.not_connected': 'Niepołączone',
    'account.created': 'Konto utworzone',
    'account.settings': 'Ustawienia',
    'account.change_password': 'Zmień hasło',
    'account.quick_links': 'Szybkie linki',
    'account.my_team': 'Moja drużyna',
    'account.logout': 'Wyloguj się',
    'account.language': 'Język',
    'account.language_polish': 'Polski',
    'account.language_english': 'English',
    
    // Auth
    'auth.login': 'Zaloguj się',
    'auth.register': 'Zarejestruj się',
    'auth.subtitle': 'Dołącz do Feather Cup i weź udział w rozgrywkach',
    'auth.steam_login': 'Zaloguj przez Steam',
    'auth.or': 'lub',
    'auth.nickname': 'Nick',
    'auth.nickname_placeholder': 'Twój nick',
    'auth.email': 'Email',
    'auth.email_placeholder': 'twoj@email.com',
    'auth.password': 'Hasło',
    'auth.password_placeholder': '••••••••',
    'auth.no_account': 'Nie masz konta? Zarejestruj się',
    'auth.have_account': 'Masz już konto? Zaloguj się',
    'auth.login_error': 'Błąd logowania',
    'auth.register_error': 'Błąd rejestracji',
    'auth.invalid_credentials': 'Nieprawidłowy email lub hasło',
    'auth.user_exists': 'Użytkownik o tym adresie email już istnieje',
    'auth.logged_in': 'Zalogowano pomyślnie!',
    'auth.account_created': 'Konto utworzone!',
    'auth.can_login': 'Możesz się teraz zalogować.',
    'auth.steam_error': 'Nie udało się połączyć ze Steam',
    'auth.logged_out': 'Wylogowano pomyślnie',
    'auth.steam_linked': 'Konto Steam połączone!',
    'auth.steam_linked_desc': 'Możesz teraz tworzyć i dołączać do drużyn.',
    'auth.error': 'Błąd',
    
    // Contact
    'contact.title': 'Kontakt',
    'contact.subtitle': 'Masz pytania? Skontaktuj się z nami, a odpowiemy najszybciej jak to możliwe',
    'contact.name': 'Imię i nazwisko',
    'contact.name_placeholder': 'Jan Kowalski',
    'contact.email': 'Adres e-mail',
    'contact.email_placeholder': 'jan@example.com',
    'contact.discord_id': 'Discord ID',
    'contact.discord_placeholder': 'nazwa#1234 lub ID użytkownika',
    'contact.subject': 'Temat',
    'contact.subject_placeholder': 'W czym możemy pomóc?',
    'contact.message': 'Wiadomość',
    'contact.message_placeholder': 'Opisz szczegółowo swoje pytanie lub problem...',
    'contact.send': 'Wyślij wiadomość',
    'contact.sending': 'Wysyłanie...',
    'contact.success': 'Wiadomość wysłana!',
    'contact.success_desc': 'Odpowiemy najszybciej jak to możliwe.',
    'contact.error': 'Błąd wysyłania',
    'contact.error_desc': 'Nie udało się wysłać wiadomości. Spróbuj ponownie później.',
    
    // Footer
    'footer.navigation': 'Nawigacja',
    'footer.information': 'Informacje',
    'footer.terms': 'Regulamin',
    'footer.privacy': 'Polityka prywatności',
    'footer.faq': 'FAQ',
    'footer.support': 'Wsparcie',
    
    // Index/Home page
    'home.register_team': 'Zapisz swoją drużynę',
    'home.view_schedule': 'Zobacz harmonogram',
    'home.prize_pool': 'Pula nagród',
    'home.teams': 'Drużyny',
    'home.tournament_days': 'Dni turnieju',
    'home.matches': 'Mecze',
    'home.upcoming_matches': 'Nadchodzące mecze',
    'home.upcoming_subtitle': 'Nie przegap kolejnych emocji',
    'home.view_all': 'Zobacz wszystkie',
    'home.no_upcoming': 'Brak nadchodzących meczów',
    'home.recent_results': 'Ostatnie wyniki',
    'home.recent_subtitle': 'Zobacz jak zakończyły się poprzednie mecze',
    'home.all_results': 'Wszystkie wyniki',
    'home.no_finished': 'Brak zakończonych meczów',
    'home.cta_title': 'Gotowy na wyzwanie?',
    'home.cta_desc': 'Zarejestruj swoją drużynę już dziś i weź udział w',
    'home.cta_suffix': 'Nagrody, sława i niezapomniane emocje czekają!',
    'home.sponsors': 'Nasi Sponsorzy',
    
    // Teams page
    'teams.title': 'Drużyny',
    'teams.subtitle': 'Poznaj wszystkie drużyny biorące udział w Feather Cup 2024',
    'teams.no_teams': 'Brak zarejestrowanych drużyn. Bądź pierwszy i zapisz swoją drużynę!',
    'teams.members': 'członków',
    'teams.status.ready': 'Gotowa',
    'teams.status.preparing': 'W przygotowaniu',
    'teams.status.registered': 'Zarejestrowana',
    
    // Team Details
    'team.not_found': 'Drużyna nie znaleziona',
    'team.back_to_list': 'Wróć do listy drużyn',
    'team.all_teams': 'Wszystkie drużyny',
    'team.players': 'Gracze',
    'team.reserves': 'Rezerwowi',
    'team.coach': 'Trener',
    'team.no_players': 'Brak graczy',
    'team.no_reserves': 'Brak rezerwowych',
    'team.no_coach': 'Brak trenera',
    'team.role.player': 'Gracz',
    'team.role.reserve': 'Rezerwowy',
    'team.role.coach': 'Trener',
    'team.status.ready_tournament': 'Gotowa do turnieju',
    
    // Matches page
    'matches.title': 'Harmonogram meczów',
    'matches.subtitle': 'Śledź nadchodzące mecze i bądź na bieżąco z rozgrywkami Feather Cup',
    'matches.bracket': 'Drabinka',
    'matches.list': 'Lista',
    'matches.upcoming': 'Nadchodzące mecze',
    'matches.finished': 'Zakończone mecze',
    'matches.no_matches': 'Brak meczów do wyświetlenia. Harmonogram zostanie wkrótce uzupełniony!',
    'matches.status.upcoming': 'Nadchodzący',
    'matches.status.live': 'LIVE',
    'matches.status.finished': 'Zakończony',
    
    // Results page
    'results.title': 'Wyniki meczów',
    'results.subtitle': 'Sprawdź wszystkie zakończone mecze i rezultaty rozgrywek na żywo',
    'results.live_matches': 'Mecze na żywo',
    'results.live': 'Na żywo',
    'results.finished_matches': 'Zakończone mecze',
    'results.winner': 'Zwycięzca',
    'results.no_matches': 'Brak zakończonych meczów. Turniej jeszcze się nie rozpoczął!',
    
    // My Team page
    'myteam.title': 'Moja Drużyna',
    'myteam.subtitle': 'Zarządzaj swoją drużyną i przygotuj się do turnieju',
    'myteam.steam_required': 'Wymagane połączenie Steam',
    'myteam.steam_required_desc': 'Aby utworzyć drużynę lub dołączyć jako członek, musisz najpierw połączyć swoje konto Steam.',
    'myteam.connect_steam': 'Połącz konto Steam',
    'myteam.registration_closed': 'Rejestracja zamknięta',
    'myteam.max_teams_reached': 'Osiągnięto maksymalną liczbę drużyn w turnieju',
    'myteam.follow_us': 'Śledź nas, aby być na bieżąco z przyszłymi turniejami!',
    'myteam.no_team': 'Nie masz jeszcze drużyny',
    'myteam.create_team_desc': 'Utwórz drużynę, aby wziąć udział w turnieju Feather Cup',
    'myteam.registered_teams': 'Zarejestrowanych drużyn',
    'myteam.create_team': 'Utwórz drużynę',
    'myteam.new_team': 'Nowa drużyna',
    'myteam.payment_redirect': 'Po wpisaniu nazwy zostaniesz przekierowany do płatności wpisowego (50 PLN)',
    'myteam.team_name': 'Nazwa drużyny',
    'myteam.team_name_placeholder': 'np. Phoenix Rising',
    'myteam.cancel': 'Anuluj',
    'myteam.create_and_pay': 'Utwórz i zapłać 50 PLN',
    'myteam.pay_fee': 'Zapłać wpisowe (50 PLN)',
    'myteam.requirements': 'Wymagania składu',
    'myteam.players': 'Gracze',
    'myteam.reserves': 'Rezerwowi',
    'myteam.coach': 'Trener',
    'myteam.add_member': 'Dodaj członka drużyny',
    'myteam.nickname': 'Pseudonim',
    'myteam.nickname_placeholder': 'Pseudonim gracza',
    'myteam.steam_id': 'Steam64 ID',
    'myteam.steam_id_placeholder': '7656119...',
    'myteam.steam_id_help': 'Format Steam64 (17 cyfr, np. 76561198012345678)',
    'myteam.role': 'Rola',
    'myteam.role_player': 'Gracz',
    'myteam.role_reserve': 'Rezerwowy',
    'myteam.role_coach': 'Trener',
    'myteam.position': 'Pozycja (opcjonalnie)',
    'myteam.position_placeholder': 'np. AWP, IGL',
    'myteam.add_member_btn': 'Dodaj członka',
    'myteam.team_members': 'Skład drużyny',
    'myteam.remove_member': 'Usuń',
    'myteam.payment_cancelled': 'Płatność anulowana',
    'myteam.payment_cancelled_desc': 'Możesz spróbować ponownie w dowolnym momencie.',
    'myteam.payment_success': 'Płatność zakończona!',
    'myteam.payment_success_desc': 'Twoja drużyna została utworzona i opłacona.',
    'myteam.payment_error': 'Błąd weryfikacji',
    'myteam.payment_error_desc': 'Nie udało się zweryfikować płatności. Spróbuj odświeżyć stronę.',
    'myteam.payment_error_2': 'Błąd płatności',
    'myteam.error': 'Błąd',
    'myteam.team_exists': 'Drużyna o tej nazwie już istnieje',
    'myteam.member_added': 'Członek dodany!',
    'myteam.member_removed': 'Członek usunięty',
    'myteam.steam_id_required': 'Wymagane Steam ID',
    'myteam.steam_id_required_desc': 'Każdy członek drużyny musi mieć podane Steam ID.',
    'myteam.steam_id_invalid': 'Nieprawidłowe Steam ID',
    'myteam.steam_id_invalid_desc': 'Steam ID musi być w formacie Steam64 (17 cyfr, zaczyna się od 7656119).',
    'myteam.steam_id_used': 'Steam ID już w użyciu',
    'myteam.steam_id_used_desc': 'Ten Steam ID jest już przypisany do innego członka drużyny.',
    'myteam.status.ready': 'Gotowa',
    'myteam.status.registered': 'Zarejestrowana',
    'myteam.status.preparing': 'W przygotowaniu',
    'myteam.paid': 'Opłacona',
    
    // Common
    'common.loading': 'Ładowanie...',
    'common.save': 'Zapisz',
    'common.cancel': 'Anuluj',
    'common.edit': 'Edytuj',
    'common.delete': 'Usuń',
    'common.back': 'Powrót',
    'common.tbd': 'TBD',
    'common.vs': 'VS',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.matches': 'Matches',
    'nav.results': 'Results',
    'nav.teams': 'Teams',
    'nav.contact': 'Contact',
    'nav.login': 'Log in',
    'nav.register_team': 'Register team',
    
    // Account page
    'account.title': 'My Account',
    'account.steam_connection': 'Steam Connection',
    'account.steam_connected': 'Steam account connected',
    'account.steam_not_connected': 'Steam account not connected',
    'account.steam_required': 'To create a team or join as a member, you must connect your Steam account.',
    'account.connect_steam': 'Connect Steam account',
    'account.info': 'Account information',
    'account.email': 'Email',
    'account.nickname': 'Nickname',
    'account.steam': 'Steam',
    'account.connected': 'Connected',
    'account.not_connected': 'Not connected',
    'account.created': 'Account created',
    'account.settings': 'Settings',
    'account.change_password': 'Change password',
    'account.quick_links': 'Quick links',
    'account.my_team': 'My team',
    'account.logout': 'Log out',
    'account.language': 'Language',
    'account.language_polish': 'Polski',
    'account.language_english': 'English',
    
    // Auth
    'auth.login': 'Log in',
    'auth.register': 'Register',
    'auth.subtitle': 'Join Feather Cup and participate in the tournament',
    'auth.steam_login': 'Log in with Steam',
    'auth.or': 'or',
    'auth.nickname': 'Nickname',
    'auth.nickname_placeholder': 'Your nickname',
    'auth.email': 'Email',
    'auth.email_placeholder': 'your@email.com',
    'auth.password': 'Password',
    'auth.password_placeholder': '••••••••',
    'auth.no_account': "Don't have an account? Register",
    'auth.have_account': 'Already have an account? Log in',
    'auth.login_error': 'Login error',
    'auth.register_error': 'Registration error',
    'auth.invalid_credentials': 'Invalid email or password',
    'auth.user_exists': 'A user with this email already exists',
    'auth.logged_in': 'Logged in successfully!',
    'auth.account_created': 'Account created!',
    'auth.can_login': 'You can now log in.',
    'auth.steam_error': 'Could not connect to Steam',
    'auth.logged_out': 'Logged out successfully',
    'auth.steam_linked': 'Steam account connected!',
    'auth.steam_linked_desc': 'You can now create and join teams.',
    'auth.error': 'Error',
    
    // Contact
    'contact.title': 'Contact',
    'contact.subtitle': 'Have questions? Get in touch with us and we will respond as soon as possible',
    'contact.name': 'Full name',
    'contact.name_placeholder': 'John Doe',
    'contact.email': 'Email address',
    'contact.email_placeholder': 'john@example.com',
    'contact.discord_id': 'Discord ID',
    'contact.discord_placeholder': 'username#1234 or user ID',
    'contact.subject': 'Subject',
    'contact.subject_placeholder': 'How can we help?',
    'contact.message': 'Message',
    'contact.message_placeholder': 'Describe your question or problem in detail...',
    'contact.send': 'Send message',
    'contact.sending': 'Sending...',
    'contact.success': 'Message sent!',
    'contact.success_desc': 'We will respond as soon as possible.',
    'contact.error': 'Sending error',
    'contact.error_desc': 'Failed to send message. Please try again later.',
    
    // Footer
    'footer.navigation': 'Navigation',
    'footer.information': 'Information',
    'footer.terms': 'Terms of Service',
    'footer.privacy': 'Privacy Policy',
    'footer.faq': 'FAQ',
    'footer.support': 'Support',
    
    // Index/Home page
    'home.register_team': 'Register your team',
    'home.view_schedule': 'View schedule',
    'home.prize_pool': 'Prize pool',
    'home.teams': 'Teams',
    'home.tournament_days': 'Tournament days',
    'home.matches': 'Matches',
    'home.upcoming_matches': 'Upcoming matches',
    'home.upcoming_subtitle': "Don't miss the next excitement",
    'home.view_all': 'View all',
    'home.no_upcoming': 'No upcoming matches',
    'home.recent_results': 'Recent results',
    'home.recent_subtitle': 'See how previous matches ended',
    'home.all_results': 'All results',
    'home.no_finished': 'No finished matches',
    'home.cta_title': 'Ready for the challenge?',
    'home.cta_desc': 'Register your team today and participate in',
    'home.cta_suffix': 'Prizes, fame, and unforgettable emotions await!',
    'home.sponsors': 'Our Sponsors',
    
    // Teams page
    'teams.title': 'Teams',
    'teams.subtitle': 'Meet all teams participating in Feather Cup 2024',
    'teams.no_teams': 'No registered teams. Be the first and register your team!',
    'teams.members': 'members',
    'teams.status.ready': 'Ready',
    'teams.status.preparing': 'Preparing',
    'teams.status.registered': 'Registered',
    
    // Team Details
    'team.not_found': 'Team not found',
    'team.back_to_list': 'Back to teams list',
    'team.all_teams': 'All teams',
    'team.players': 'Players',
    'team.reserves': 'Reserves',
    'team.coach': 'Coach',
    'team.no_players': 'No players',
    'team.no_reserves': 'No reserves',
    'team.no_coach': 'No coach',
    'team.role.player': 'Player',
    'team.role.reserve': 'Reserve',
    'team.role.coach': 'Coach',
    'team.status.ready_tournament': 'Ready for tournament',
    
    // Matches page
    'matches.title': 'Match Schedule',
    'matches.subtitle': 'Follow upcoming matches and stay up to date with Feather Cup games',
    'matches.bracket': 'Bracket',
    'matches.list': 'List',
    'matches.upcoming': 'Upcoming matches',
    'matches.finished': 'Finished matches',
    'matches.no_matches': 'No matches to display. The schedule will be updated soon!',
    'matches.status.upcoming': 'Upcoming',
    'matches.status.live': 'LIVE',
    'matches.status.finished': 'Finished',
    
    // Results page
    'results.title': 'Match Results',
    'results.subtitle': 'Check all finished matches and live results',
    'results.live_matches': 'Live matches',
    'results.live': 'Live',
    'results.finished_matches': 'Finished matches',
    'results.winner': 'Winner',
    'results.no_matches': 'No finished matches. The tournament has not started yet!',
    
    // My Team page
    'myteam.title': 'My Team',
    'myteam.subtitle': 'Manage your team and prepare for the tournament',
    'myteam.steam_required': 'Steam connection required',
    'myteam.steam_required_desc': 'To create a team or join as a member, you must first connect your Steam account.',
    'myteam.connect_steam': 'Connect Steam account',
    'myteam.registration_closed': 'Registration closed',
    'myteam.max_teams_reached': 'Maximum number of teams in the tournament has been reached',
    'myteam.follow_us': 'Follow us to stay updated on future tournaments!',
    'myteam.no_team': "You don't have a team yet",
    'myteam.create_team_desc': 'Create a team to participate in the Feather Cup tournament',
    'myteam.registered_teams': 'Registered teams',
    'myteam.create_team': 'Create team',
    'myteam.new_team': 'New team',
    'myteam.payment_redirect': 'After entering the name, you will be redirected to pay the entry fee (50 PLN)',
    'myteam.team_name': 'Team name',
    'myteam.team_name_placeholder': 'e.g. Phoenix Rising',
    'myteam.cancel': 'Cancel',
    'myteam.create_and_pay': 'Create and pay 50 PLN',
    'myteam.pay_fee': 'Pay entry fee (50 PLN)',
    'myteam.requirements': 'Roster requirements',
    'myteam.players': 'Players',
    'myteam.reserves': 'Reserves',
    'myteam.coach': 'Coach',
    'myteam.add_member': 'Add team member',
    'myteam.nickname': 'Nickname',
    'myteam.nickname_placeholder': 'Player nickname',
    'myteam.steam_id': 'Steam64 ID',
    'myteam.steam_id_placeholder': '7656119...',
    'myteam.steam_id_help': 'Steam64 format (17 digits, e.g. 76561198012345678)',
    'myteam.role': 'Role',
    'myteam.role_player': 'Player',
    'myteam.role_reserve': 'Reserve',
    'myteam.role_coach': 'Coach',
    'myteam.position': 'Position (optional)',
    'myteam.position_placeholder': 'e.g. AWP, IGL',
    'myteam.add_member_btn': 'Add member',
    'myteam.team_members': 'Team roster',
    'myteam.remove_member': 'Remove',
    'myteam.payment_cancelled': 'Payment cancelled',
    'myteam.payment_cancelled_desc': 'You can try again at any time.',
    'myteam.payment_success': 'Payment completed!',
    'myteam.payment_success_desc': 'Your team has been created and paid for.',
    'myteam.payment_error': 'Verification error',
    'myteam.payment_error_desc': 'Failed to verify payment. Please refresh the page.',
    'myteam.payment_error_2': 'Payment error',
    'myteam.error': 'Error',
    'myteam.team_exists': 'A team with this name already exists',
    'myteam.member_added': 'Member added!',
    'myteam.member_removed': 'Member removed',
    'myteam.steam_id_required': 'Steam ID required',
    'myteam.steam_id_required_desc': 'Every team member must have a Steam ID.',
    'myteam.steam_id_invalid': 'Invalid Steam ID',
    'myteam.steam_id_invalid_desc': 'Steam ID must be in Steam64 format (17 digits, starts with 7656119).',
    'myteam.steam_id_used': 'Steam ID already in use',
    'myteam.steam_id_used_desc': 'This Steam ID is already assigned to another team member.',
    'myteam.status.ready': 'Ready',
    'myteam.status.registered': 'Registered',
    'myteam.status.preparing': 'Preparing',
    'myteam.paid': 'Paid',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.back': 'Back',
    'common.tbd': 'TBD',
    'common.vs': 'VS',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'pl';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
